# Generated by Django 4.0.4 on 2022-04-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, default='SOME STRING', max_length=225),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='SOME STRING', max_length=255, unique=True),
        ),
    ]
