# Generated by Django 4.0.4 on 2022-05-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/def.jpg', upload_to='images/'),
        ),
    ]
